-- 0005_edge_weight.sql
--
-- 给 `edges` 补一个通行权重 `weight`。
--
-- 为什么需要它（而不是只用 `length_m`）：
--   路径规划的最小化目标是**通行时间**，而 `length_m / speed_limit_mps` 假设「长度就是代价」。
--   现实里同一段长度可能更贵：施工占道、限流、路面差、早晚高峰。这些既不是长度（不能谎报
--   物理距离），也不是限速（限速是交规事实，不该为了表达拥堵而被改写），必须有自己的列。
--   加上它之后「两条长度相同的路哪条更快」才可表达，算法对比（M4）也才有可比的数据。
--
-- 为什么约束是 `weight >= 1` 而不是 `weight > 0`：
--   A* 的启发式是「欧氏直线距离 ÷ 全网最高速度」，它只有在**边的代价 ≥ 未加权代价**时
--   才不高估剩余代价。允许 `weight < 1` 会让启发式变成高估，A* 于是会返回一条
--   非最优路线 —— 而且不会报错，只是「偶尔绕远」。权重因此定义为**只增不减的惩罚系数**：
--   1 = 畅通（缺省），越大越慢。
--
-- 为什么直接 ADD COLUMN：新增列且带非空缺省值，不破坏既有读写（与 0004 同一理由）。
-- SQLite 的 `ALTER TABLE ... ADD COLUMN` 不允许带 PRIMARY KEY / UNIQUE，但允许
-- NOT NULL + DEFAULT 与 CHECK，本列两者都用上了。

ALTER TABLE edges ADD COLUMN weight REAL NOT NULL DEFAULT 1 CHECK (weight >= 1);
